name       : xmltoman
version    : 0.6
release    : 1
source     :
    - https://github.com/atsb/xmltoman/archive/refs/tags/0.6.tar.gz : cdd5063ca8beb6fe51ec6ab85f70d31fc8ed034e85e32dd9b7c0b7142bb72fb6
license    : GPL-2.0-or-later
component  : programming.tools
summary    : convert xml to groff (manpage) format
description: |
    Two very simple scripts for converting xml to groff or html.
rundeps    :
    - perl
    - libxslt
build      : |
    %make prefix=%PREFIX%
install    : |
    %make_install prefix=%PREFIX%
